//archivo ejemplo para para enviar peticiones POST, GET, INSERT, DELETE 

 POST https://www.bancaexportadora.com.co//A2_Factura_Electronica/facturaValidacionPrevia/POS/facturacionQuery.php
 authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJJZERvY3VtZW50byI6IlNFVFA5OTAwMDAwMTgiLCJzZWRlIjp7Il9pZCI6IjYyODRmODEzZWMzMjU2ZWM3N2VlNDQzYyIsIk5vbWJyZSI6IkFlcm9wdWVydG8iLCJEaXJlY2Npb24iOiJBZXJvcHVlcnRvIEludGVybmFjaW9uYWwgRWwgRG9yYWRvIC0gTXVlbGxlIG5hY2lvbmFsIEw3MiJ9LCJpYXQiOjE2NTM0MzA3OTQsImV4cCI6MTY1MzUxNzE5NH0.N3DjN--R1dXcamhxnp53pZ9NhH_7w3yyguWQedflSs0
